package com.lengjing.consumer;

import java.io.FileWriter;
import java.io.IOException;
import java.net.URLDecoder;
import java.net.URLEncoder;

import org.apache.hadoop.hbase.Cell;
import org.apache.hadoop.hbase.client.Delete;
import org.apache.hadoop.hbase.client.Result;
import org.apache.hadoop.hbase.client.ResultScanner;
import org.apache.hadoop.hbase.client.Scan;
import org.apache.hadoop.hbase.util.Bytes;
import org.dom4j.DocumentException;

/**
 * Hello world!
 *
 */
public class App 
{
    public static void main( String[] args ) throws IOException
    {
    	try {
			//解析xml数据
			try {
				//str=URLDecoder.decode(str,"utf8");
				String str="康嘉_上海拉扎斯信息科技有限公司|/lengjing/test/personPosition|1472027749345|true|<?xml version='1.0' encoding='UTF-8'?><DATA><ORDERLIST><ITEM><UID>F12A149BC9ECA4C9</UID><ORDERNO>160824163924008965725</ORDERNO><KEY>上海拉扎斯信息科技有限公司-康嘉</KEY><KEYTYPE>10</KEYTYPE><STATUS>1</STATUS><FINISHTIME>2016-08-24 16:36:33</FINISHTIME></ITEM></ORDERLIST><RYPOSFR><ITEM><RYNAME>康嘉</RYNAME><ENTNAME>西安微远餐饮管理有限公司</ENTNAME><REGNO>610131100066215</REGNO><ENTTYPE>有限责任公司（自然人投资或控股）</ENTTYPE><REGCAP>100.000000</REGCAP><REGCAPCUR>人民币</REGCAPCUR><ENTSTATUS>在营（开业）</ENTSTATUS></ITEM></RYPOSFR><RYPOSSHA><ITEM><RYNAME>康嘉</RYNAME><ENTNAME>上海拉扎斯信息科技有限公司</ENTNAME><REGNO>310112000993231</REGNO><ENTTYPE>有限责任公司</ENTTYPE><REGCAP>417.000000</REGCAP><REGCAPCUR>人民币</REGCAPCUR><SUBCONAM></SUBCONAM><CURRENCY></CURRENCY><CONFORM></CONFORM><FUNDEDRATIO>〈0.01%</FUNDEDRATIO><ENTSTATUS>在营（开业）</ENTSTATUS></ITEM><ITEM><RYNAME>康嘉</RYNAME><ENTNAME>西安微远餐饮管理有限公司</ENTNAME><REGNO>610131100066215</REGNO><ENTTYPE>有限责任公司（自然人投资或控股）</ENTTYPE><REGCAP>100.000000</REGCAP><REGCAPCUR>人民币</REGCAPCUR><SUBCONAM></SUBCONAM><CURRENCY></CURRENCY><CONFORM></CONFORM><FUNDEDRATIO>〈0.01%</FUNDEDRATIO><ENTSTATUS>在营（开业）</ENTSTATUS></ITEM></RYPOSSHA><RYPOSPER><ITEM><RYNAME>康嘉</RYNAME><ENTNAME>上海馔山餐饮管理有限公司</ENTNAME><REGNO>310107000811513</REGNO><ENTTYPE>有限责任公司（法人独资）</ENTTYPE><REGCAP>2100.000000</REGCAP><REGCAPCUR>人民币</REGCAPCUR><ENTSTATUS>在营（开业）</ENTSTATUS><POSITION>董事</POSITION></ITEM><ITEM><RYNAME>康嘉</RYNAME><ENTNAME>拉扎斯网络科技（上海）有限公司</ENTNAME><REGNO>310000400663743</REGNO><ENTTYPE>有限责任公司（台港澳法人独资）</ENTTYPE><REGCAP>750000.000000</REGCAP><REGCAPCUR>人民币</REGCAPCUR><ENTSTATUS>在营（开业）</ENTSTATUS><POSITION>董事</POSITION></ITEM><ITEM><RYNAME>康嘉</RYNAME><ENTNAME>上海拉扎斯信息科技有限公司</ENTNAME><REGNO>310112000993231</REGNO><ENTTYPE>有限责任公司</ENTTYPE><REGCAP>417.000000</REGCAP><REGCAPCUR>人民币</REGCAPCUR><ENTSTATUS>在营（开业）</ENTSTATUS><POSITION>董事</POSITION></ITEM><ITEM><RYNAME>康嘉</RYNAME><ENTNAME>西安微远餐饮管理有限公司</ENTNAME><REGNO>610131100066215</REGNO><ENTTYPE>有限责任公司（自然人投资或控股）</ENTTYPE><REGCAP>100.000000</REGCAP><REGCAPCUR>人民币</REGCAPCUR><ENTSTATUS>在营（开业）</ENTSTATUS><POSITION>董事长</POSITION></ITEM></RYPOSPER><PUNISHBREAK></PUNISHBREAK><PERSONCASEINFO></PERSONCASEINFO></DATA>";
				//String str="王李海|33041919640716621X|/lengjing/test/searchByIDCard|1472112411642||<?xml version='1.0' encoding='UTF-8'?><DATA><ORDERLIST><ITEM><UID>F12A149BC9ECA4C9</UID><ORDERNO>160825161224458272169</ORDERNO><KEY>33041919640716621X</KEY><KEYTYPE>9</KEYTYPE><STATUS>1</STATUS><FINISHTIME>2016-08-25 16:12:24</FINISHTIME></ITEM></ORDERLIST><RYPOSFR><ITEM><RYNAME>王李海</RYNAME><ENTNAME>海宁兴龙家居用品有限公司</ENTNAME><REGNO>330481000053361</REGNO><ENTTYPE>私营有限责任公司（自然人控股或私营性质企业控股）</ENTTYPE><REGCAP>1000.000000</REGCAP><REGCAPCUR>人民币</REGCAPCUR><ENTSTATUS>在营（开业）</ENTSTATUS></ITEM><ITEM><RYNAME>王李海</RYNAME><ENTNAME>浙江维龙家居用品有限公司</ENTNAME><REGNO>330400400015951</REGNO><ENTTYPE>有限责任公司（中外合资）</ENTTYPE><REGCAP>390.000000</REGCAP><REGCAPCUR>美元</REGCAPCUR><ENTSTATUS>在营（开业）</ENTSTATUS></ITEM><ITEM><RYNAME>王李海</RYNAME><ENTNAME>海盐金茂服饰有限公司</ENTNAME><REGNO>330424000008360</REGNO><ENTTYPE>私营有限责任公司（自然人控股或私营性质企业控股）</ENTTYPE><REGCAP>50.000000</REGCAP><REGCAPCUR>人民币</REGCAPCUR><ENTSTATUS>在营（开业）</ENTSTATUS></ITEM></RYPOSFR><RYPOSSHA><ITEM><RYNAME>王李海</RYNAME><ENTNAME>海宁兴龙家居用品有限公司</ENTNAME><REGNO>330481000053361</REGNO><ENTTYPE>私营有限责任公司（自然人控股或私营性质企业控股）</ENTTYPE><REGCAP>1000.000000</REGCAP><REGCAPCUR>人民币</REGCAPCUR><SUBCONAM></SUBCONAM><CURRENCY></CURRENCY><CONFORM></CONFORM><FUNDEDRATIO>〈0.01%</FUNDEDRATIO><ENTSTATUS>在营（开业）</ENTSTATUS></ITEM><ITEM><RYNAME>王李海</RYNAME><ENTNAME>海盐金茂服饰有限公司</ENTNAME><REGNO>330424000008360</REGNO><ENTTYPE>私营有限责任公司（自然人控股或私营性质企业控股）</ENTTYPE><REGCAP>50.000000</REGCAP><REGCAPCUR>人民币</REGCAPCUR><SUBCONAM></SUBCONAM><CURRENCY></CURRENCY><CONFORM></CONFORM><FUNDEDRATIO>〈0.01%</FUNDEDRATIO><ENTSTATUS>在营（开业）</ENTSTATUS></ITEM></RYPOSSHA><RYPOSPER><ITEM><RYNAME>王李海</RYNAME><ENTNAME>海宁兴龙家居用品有限公司</ENTNAME><REGNO>330481000053361</REGNO><ENTTYPE>私营有限责任公司（自然人控股或私营性质企业控股）</ENTTYPE><REGCAP>1000.000000</REGCAP><REGCAPCUR>人民币</REGCAPCUR><ENTSTATUS>在营（开业）</ENTSTATUS><POSITION>总经理</POSITION></ITEM><ITEM><RYNAME>王李海</RYNAME><ENTNAME>海宁兴龙家居用品有限公司</ENTNAME><REGNO>330481000053361</REGNO><ENTTYPE>私营有限责任公司（自然人控股或私营性质企业控股）</ENTTYPE><REGCAP>1000.000000</REGCAP><REGCAPCUR>人民币</REGCAPCUR><ENTSTATUS>在营（开业）</ENTSTATUS><POSITION>执行董事</POSITION></ITEM><ITEM><RYNAME>王李海</RYNAME><ENTNAME>海宁兴龙家居用品有限公司</ENTNAME><REGNO>330481000053361</REGNO><ENTTYPE>私营有限责任公司（自然人控股或私营性质企业控股）</ENTTYPE><REGCAP>1000.000000</REGCAP><REGCAPCUR>人民币</REGCAPCUR><ENTSTATUS>在营（开业）</ENTSTATUS><POSITION>执行董事</POSITION></ITEM><ITEM><RYNAME>王李海</RYNAME><ENTNAME>浙江维龙家居用品有限公司</ENTNAME><REGNO>330400400015951</REGNO><ENTTYPE>有限责任公司（中外合资）</ENTTYPE><REGCAP>390.000000</REGCAP><REGCAPCUR>美元</REGCAPCUR><ENTSTATUS>在营（开业）</ENTSTATUS><POSITION>董事长</POSITION></ITEM><ITEM><RYNAME>王李海</RYNAME><ENTNAME>浙江维龙家居用品有限公司</ENTNAME><REGNO>330400400015951</REGNO><ENTTYPE>有限责任公司（中外合资）</ENTTYPE><REGCAP>390.000000</REGCAP><REGCAPCUR>美元</REGCAPCUR><ENTSTATUS>在营（开业）</ENTSTATUS><POSITION>董事长</POSITION></ITEM><ITEM><RYNAME>王李海</RYNAME><ENTNAME>浙江维龙家居用品有限公司</ENTNAME><REGNO>330400400015951</REGNO><ENTTYPE>有限责任公司（中外合资）</ENTTYPE><REGCAP>390.000000</REGCAP><REGCAPCUR>美元</REGCAPCUR><ENTSTATUS>在营（开业）</ENTSTATUS><POSITION>总经理</POSITION></ITEM><ITEM><RYNAME>王李海</RYNAME><ENTNAME>海盐金茂服饰有限公司</ENTNAME><REGNO>330424000008360</REGNO><ENTTYPE>私营有限责任公司（自然人控股或私营性质企业控股）</ENTTYPE><REGCAP>50.000000</REGCAP><REGCAPCUR>人民币</REGCAPCUR><ENTSTATUS>在营（开业）</ENTSTATUS><POSITION>执行董事</POSITION></ITEM><ITEM><RYNAME>王李海</RYNAME><ENTNAME>海盐金茂服饰有限公司</ENTNAME><REGNO>330424000008360</REGNO><ENTTYPE>私营有限责任公司（自然人控股或私营性质企业控股）</ENTTYPE><REGCAP>50.000000</REGCAP><REGCAPCUR>人民币</REGCAPCUR><ENTSTATUS>在营（开业）</ENTSTATUS><POSITION>执行董事</POSITION></ITEM><ITEM><RYNAME>王李海</RYNAME><ENTNAME>海盐金茂服饰有限公司</ENTNAME><REGNO>330424000008360</REGNO><ENTTYPE>私营有限责任公司（自然人控股或私营性质企业控股）</ENTTYPE><REGCAP>50.000000</REGCAP><REGCAPCUR>人民币</REGCAPCUR><ENTSTATUS>在营（开业）</ENTSTATUS><POSITION>经理</POSITION></ITEM><ITEM><RYNAME>王李海</RYNAME><ENTNAME>海宁市维龙进出口有限公司</ENTNAME><REGNO>330481000197778</REGNO><ENTTYPE>一人有限责任公司（外商投资企业法人独资）</ENTTYPE><REGCAP>100.000000</REGCAP><REGCAPCUR>人民币</REGCAPCUR><ENTSTATUS>在营（开业）</ENTSTATUS><POSITION>监事</POSITION></ITEM><ITEM><RYNAME>王李海</RYNAME><ENTNAME>海宁市玖怡时装有限公司</ENTNAME><REGNO>330481000127134</REGNO><ENTTYPE>一人有限责任公司（私营法人独资）</ENTTYPE><REGCAP>10.000000</REGCAP><REGCAPCUR>人民币</REGCAPCUR><ENTSTATUS>在营（开业）</ENTSTATUS><POSITION>监事</POSITION></ITEM></RYPOSPER><PERSONCASEINFO></PERSONCASEINFO></DATA>";
				System.out.println(str);
				String value=str.substring(0,str.indexOf("<?xml"));
				String personName="";
				String companyname="";
				String name=value.split("\\|")[0];
				String idcard="";
				if(name.indexOf("_")>0){
					personName=name.split("_")[0];
					companyname=name.split("_")[1];
				}else{
					personName=name;
					companyname=value.split("\\|")[1];
					idcard=value.split("\\|")[1];
				}
				String valuexml=str.substring(str.indexOf("<?xml"));
				XmlParse.parse(valuexml,personName,companyname,idcard);
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		} catch (DocumentException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }
}
